#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

quarkus:

  application:
    name: Polaris

  banner:
    path: polaris-banner.txt

  config:
    mapping:
      validate-unknown: true

  log:
    level: INFO
    category:
      "org.apache.polaris":
        level: DEBUG
      "org.apache.iceberg.rest":
        level: DEBUG
    console:
      enable: true
      level: INFO
      format: '%-5p [%d{yyyy-MM-dd HH:mm:ss,SSS} - %-6r] [%t] [%X{aid}%X{sid}%X{tid}%X{wid}%X{oid}%X{srv}%X{job}%X{rid}] %c{30}: %m %kvp%n%ex'
      json: false
    file:
      enable: true
      json: false
      level: INFO
      format: '%-5p [%d{yyyy-MM-dd HH:mm:ss,SSS} - %-6r] [%t] [%X{aid}%X{sid}%X{tid}%X{wid}%X{oid}%X{srv}%X{job}%X{rid}] %c{30}: %m %kvp%n%ex'
      path: ./logs/polaris.log
      rotation:
        file-suffix: .yyyy-MM-dd.gz
        max-backup-index: 14
        max-file-size: 10M

  http:
    port: 8181
    test-port: 0
    access-log:
      enabled: true
    auth:
      basic: false
    limits:
      max-body-size: 10240K
    cors:
      headers: '*'
      access-control-max-age: PT10M
      access-control-allow-credentials: true
      methods: PATCH, POST, DELETE, GET, PUT
      origins: http://localhost:8080
      exposed-headers: '*'
    body:
      handle-file-uploads: false
    enable-decompression: true
    compress-media-types: application/json,text/html,text/plain
    enable-compression: true

  management:
    enabled: true
    port: 8182
    test-port: 0

polaris:

  context:
    default-realm: default-realm
    call-context-resolver:
      type: default
    realm-context-resolver:
      type: default

  persistence:
    metastore-manager:
      type: in-memory

  io:
    file-io-factory:
      type: wasb

  tasks:
    thread-name-pattern: taskHandler-%d
    pool-size: 10
    fixed-size: true

  # FIXME the whole PolarisConfigurationStore + PolarisConfiguration needs to be refactored
  # to become a proper Quarkus configuration object
  # For now this has to be in a YAML file to preserve type information
  config:
    feature-configurations:
      ENFORCE_PRINCIPAL_CREDENTIAL_ROTATION_REQUIRED_CHECKING: false
      SUPPORTED_CATALOG_STORAGE_TYPES: [ S3, GCS, AZURE, FILE ]

  # FIXME these were created to make CDI happy, see PolarisStorageIntegrationProviderImpl
  storage:
    gcp:
      token: cafebabe
      lifespan: PT1H
    aws:
      awsAccessKey: access-key
      awsSecretKey: secret-key

  # TODO wire up the below properties

  authenticator:
    type: org.apache.polaris.service.auth.TestInlineBearerTokenPolarisAuthenticator
  oauth2:
    type: test
  rateLimiter:
    type: no-op
