
# FIXME the whole PolarisConfigurationStore + PolarisConfiguration needs to be refactored
# to become a proper Quarkus configuration object
# For now this has to be in a YAML file to preserve type information
polaris.config.feature-configurations:
  ENFORCE_PRINCIPAL_CREDENTIAL_ROTATION_REQUIRED_CHECKING: false
  SUPPORTED_CATALOG_STORAGE_TYPES: [S3, GCS, AZURE, FILE]
